### ISSUE TITLE
Metrics library is out of date 

### ISSUE THREAD

**Issue by felixgao** [intuit/Autumn#6]
yammer.metric have been moved to io.dropwizard.metrics.
http://mvnrepository.com/artifact/io.dropwizard.metrics/metrics-core

please update the library to use the latest metrics

com.yammer.metrics:metrics-core:2.1.3 -> 2.2.0
--- com.yammer.metrics:metrics-servlet:2.1.3
     --- com.intuit.data.autumn:autumn.web:1.0.20160315061734
          --- com.intuit.data.autumn:autumn.api:1.0.20160315061734

**Comment by jwtodd** [comment]
resolved. no?
